#########################
# Model Configurations  #
#########################

ROOT: '/srv/data/ltcl/data'
LOG: '/srv/data/ltcl/log'
DATASET: 'physics_ball_5_s1'

SPLINE:
    USE_WARM_START: TRUE
    TYPE: 'laplacian'
    STEPS: 5000
    LR: 0.001
    CUDA: FALSE
    BS: 64
    LATENT_DIM: 10
    BOUND: 5
    BINS: 8
    ORDER: 'linear'
    PATH: '/srv/data/ltcl/ckpts/spline_mbi_5_ball.pth'

VAE:
    GPU: [1]
    CPU: 8
    TRAIN_BS: 32
    VAL_BS: 256
    EPOCHS: 300
    N_VAL_SAMPLES: 1024
    NC: 3
    LAG: 2
    LENGTH: 2
    NCLASS: 1
    TRANS_PRIOR: 'L'
    BIAS: TRUE
    INFER_MODE: 'F'
    LR: 2.0e-3
    BETA: 1.0E-2
    GAMMA: 25
    SIGMA: 1.0e-7
    LATENT_DIM: 10
    CAUSAL_DIM: 10
    L1: 1.0e-1
    ENC:
        HIDDEN_DIM: 1024
    DEC:
        HIDDEN_DIM: 1024
        DIST: 'bernoulli'
    PIN: TRUE

MCC:
    FREQ: 0.1
    CORR: 'Spearman' # 'Spearman'